from __future__ import annotations
from .spec import BotSpecification


def _rules(spec: BotSpecification) -> str:
    lines = []
    for r in spec.entry_rules:
        lines.append(f"{r.indicator} {r.operator} {r.value}")
    return " and ".join(lines) or "True"


def generate_python(spec: BotSpecification) -> str:
    return f'''# Generated by Bitey SBT — sbt-bot-v1\n# Research/demo/paper only. No live orders.\nNAME = {spec.name!r}\nSYMBOL = {spec.symbol!r}\nTIMEFRAME = {spec.timeframe!r}\nENTRY_RULE = {(_rules(spec))!r}\nRISK_PCT = {spec.risk.risk_pct}\nSTOP_TYPE = {spec.risk.stop_type!r}\nSTOP_VALUE = {spec.risk.stop_value}\n\ndef signal(context):\n    # Bind context indicators to the SBT Quant Engine.\n    return "buy" if context.get("entry", False) else "hold"\n'''


def generate_mql5(spec: BotSpecification) -> str:
    return f'''// Generated by Bitey SBT — sbt-bot-v1\n// Research/demo only. Live trading is intentionally disabled.\n#property strict\ninput double RiskPct = {spec.risk.risk_pct};\ninput double StopValue = {spec.risk.stop_value};\n// Strategy: {spec.name} | {spec.symbol} | {spec.timeframe}\nvoid OnTick() {{\n   // Connect generated signals to the SBT demo/paper boundary only.\n}}\n'''


def generate_pine(spec: BotSpecification) -> str:
    return f'''//@version=6\n// Generated by Bitey SBT — sbt-bot-v1\n// Research/demo only.\nstrategy({spec.name!r}, overlay=true, initial_capital={spec.initial_capital}, pyramiding=0)\nriskPct = {spec.risk.risk_pct}\n// Indicator/rule bindings are generated from the common SBT specification.\nentry = false\nif entry\n    strategy.entry("Long", strategy.long)\n'''


def generate_typescript(spec: BotSpecification) -> str:
    return f'''// Generated by Bitey SBT — sbt-bot-v1\n// Research/demo/paper only.\nexport const bot = {{\n  name: {spec.name!r}, symbol: {spec.symbol!r}, timeframe: {spec.timeframe!r},\n  riskPct: {spec.risk.risk_pct}, stopType: {spec.risk.stop_type!r}, stopValue: {spec.risk.stop_value}\n}} as const;\n\nexport function signal(context: Record<string, unknown>): "buy" | "sell" | "hold" {{\n  return context.entry === true ? "buy" : "hold";\n}}\n'''


def generate_code(spec: BotSpecification) -> str:
    return {"python": generate_python, "mql5": generate_mql5, "pine": generate_pine, "typescript": generate_typescript}[spec.language](spec)
