(function(){
'use strict';
const API=()=>((window.SBT_API_URL||localStorage.getItem('sbt_api_base')||'https://bitey-system-bots-trading-api.onrender.com').replace(/\/$/,''));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function get(path,opts){const r=await fetch(API()+path,Object.assign({headers:{Accept:'application/json'}},opts||{}));if(!r.ok)throw Error('HTTP '+r.status);return r.json();}
function page(id){if(typeof window.page==='function')window.page(id);}
function set(id,v){const e=document.getElementById(id);if(e)e.textContent=v??'—';}
function ensureNav(){
 const nav=document.querySelector('.nav');if(!nav||nav.querySelector('[data-page="web-trader"]'))return;
 const marker=nav.querySelector('[data-page="bots"]'),b=document.createElement('button');
 b.dataset.page='web-trader';b.textContent='▣ Web Trader';
 if(marker)marker.insertAdjacentElement('afterend',b);else nav.appendChild(b);
 b.addEventListener('click',()=>page('web-trader'));
}
function avgTrueRange(c,n){if(c.length<2)return 0;const a=[];for(let i=Math.max(1,c.length-n);i<c.length;i++){const h=+c[i].high,l=+c[i].low,pc=+c[i-1].close;a.push(Math.max(h-l,Math.abs(h-pc),Math.abs(l-pc)));}return a.reduce((x,y)=>x+y,0)/(a.length||1);}
function ensureSection(){
 if(document.getElementById('web-trader'))return;
 const main=document.querySelector('.main');if(!main)return;
 const s=document.createElement('section');s.className='page';s.id='web-trader';
 s.innerHTML='<div class="hero"><span class="eyebrow">Web Trader · Market Terminal</span><h2>Web Trader</h2><p>Terminal conectado al proveedor público de mercado. Analiza precio y prepara una operación DEMO; no envía órdenes al broker.</p><div class="toolbar"><button class="btn primary" id="wtRefresh">Actualizar mercado</button><button class="btn blue" id="wtAnalyze">Analizar con SBT</button><button class="btn" id="wtPreviewBuy">Previsualizar BUY</button><button class="btn" id="wtPreviewSell">Previsualizar SELL</button></div></div><div class="form"><label>Activo<select id="wtSymbol"><option>EURUSD</option><option>GBPUSD</option><option>USDJPY</option><option>XAUUSD</option><option>BTCUSD</option><option>SPX500</option><option>NAS100</option><option>AAPL</option><option>NVDA</option></select></label><label>Timeframe<select id="wtTf"><option>M5</option><option>M15</option><option>H1</option><option>H4</option><option>D1</option></select></label></div><div class="grid" style="margin-top:14px"><div class="card metric"><span class="label">Precio</span><div class="value" id="wtPrice">—</div><span class="muted" id="wtQuoteState">Esperando consulta</span></div><div class="card metric"><span class="label">Sesgo</span><div class="value" id="wtBias">—</div><span class="muted" id="wtConfidence">—</span></div><div class="card metric"><span class="label">ATR</span><div class="value" id="wtAtr">—</div><span class="muted">Volatilidad</span></div><div class="card metric"><span class="label">Velas</span><div class="value" id="wtCandles">0</div><span class="muted">Proveedor público</span></div></div><div class="layout"><div class="card"><h3>Market chart</h3><canvas id="wtChart" height="300" style="width:100%;background:#070c12;border:1px solid #202c39;border-radius:10px"></canvas></div><div class="card"><h3>Trade preview</h3><div id="wtPreview" class="notice">Selecciona BUY o SELL para calcular SL/TP. Nada se envía al broker.</div></div></div><div class="card"><h3>SBT analysis</h3><div id="wtAnalysis" class="sub">Pulsa “Analizar con SBT”.</div></div>';
 main.appendChild(s);
 async function load(){const sym=document.getElementById('wtSymbol').value,tf=document.getElementById('wtTf').value;set('wtQuoteState','Consultando…');try{const [q,c]=await Promise.all([get('/api/v1/market/quote/'+encodeURIComponent(sym)+'?timeframe='+tf),get('/api/v1/market/candles/'+encodeURIComponent(sym)+'?timeframe='+tf+'&limit=120')]);window.__wt={symbol:sym,timeframe:tf,quote:q,candles:c.candles||[]};set('wtPrice',Number(q.last??q.price??q.bid).toFixed(5));set('wtCandles',window.__wt.candles.length);set('wtQuoteState',(q.exchange||'market')+' · '+(q.currency||''));draw();}catch(e){set('wtQuoteState','Market API unavailable');}}
 async function analyze(){try{if(!window.__wt||window.__wt.candles.length<35)await load();const x=window.__wt,a=await get('/api/v1/sbt/market-intelligence/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({symbol:x.symbol,timeframe:x.timeframe,candles:x.candles,capital:500,language:'es',event:'web_trader_analysis'})});set('wtBias',a.bias||'NEUTRAL');set('wtConfidence',a.confidence!=null?(Number(a.confidence)*100).toFixed(1)+'%':'—');const atr=a.technical?.atr?.value??a.atr;set('wtAtr',atr!=null?Number(atr).toFixed(6):'—');set('wtAnalysis',a.summary||a.explanation||JSON.stringify(a));}catch(e){set('wtAnalysis','No se pudo analizar: '+e.message);}}
 function preview(side){const x=window.__wt;if(!x||!x.candles.length){set('wtPreview','Primero actualiza el mercado.');return;}const entry=Number(x.quote.last??x.candles.at(-1).close),atr=avgTrueRange(x.candles,14),sl=side==='BUY'?entry-1.3*atr:entry+1.3*atr,tp=side==='BUY'?entry+2.6*atr:entry-2.6*atr;document.getElementById('wtPreview').innerHTML='<strong>'+side+' · DEMO PREVIEW</strong><br>Entrada '+entry.toFixed(5)+'<br>SL '+sl.toFixed(5)+'<br>TP '+tp.toFixed(5)+'<br>Riesgo lógico US$ 1.25 · RR 2.00<br><span class="small">Sin OrderSend, sin broker order.</span>';}
 function draw(){const can=document.getElementById('wtChart'),x=window.__wt;if(!can||!x)return;const dpr=devicePixelRatio||1,w=can.clientWidth||700,h=300;can.width=w*dpr;can.height=h*dpr;const ctx=can.getContext('2d');ctx.scale(dpr,dpr);const v=x.candles.slice(-80),hi=Math.max(...v.map(z=>+z.high)),lo=Math.min(...v.map(z=>+z.low)),span=hi-lo||1;ctx.clearRect(0,0,w,h);ctx.strokeStyle='#18222d';for(let i=0;i<6;i++){const y=20+i*(h-45)/5;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke();}ctx.strokeStyle='#52e6a2';ctx.lineWidth=2;ctx.beginPath();v.forEach((z,i)=>{const xx=i*(w-20)/(v.length-1)+10,yy=20+(hi-z.close)/span*(h-45);i?ctx.lineTo(xx,yy):ctx.moveTo(xx,yy);});ctx.stroke();}
 document.getElementById('wtRefresh').onclick=load;document.getElementById('wtAnalyze').onclick=analyze;document.getElementById('wtPreviewBuy').onclick=()=>preview('BUY');document.getElementById('wtPreviewSell').onclick=()=>preview('SELL');load();
}
function addAction(id,title,text,buttonText,fn){
 const p=document.getElementById(id);if(!p||p.querySelector('.sbt-action-surface'))return;
 const c=document.createElement('div');c.className='card sbt-action-surface';c.style.marginTop='14px';c.innerHTML='<h3>'+title+'</h3><p class="sub">'+text+'</p><button class="btn primary">'+buttonText+'</button><div class="result"></div>';p.appendChild(c);
 const b=c.querySelector('button'),o=c.querySelector('.result');b.onclick=async()=>{b.disabled=true;b.textContent='Ejecutando…';o.style.display='block';try{const r=await fn();o.textContent=typeof r==='string'?r:JSON.stringify(r);}catch(e){o.textContent='No disponible: '+e.message;}finally{b.disabled=false;b.textContent=buttonText;}};
}
function boot(){
 ensureNav();ensureSection();
 addAction('research','Research Lab · ejecución','Consulta una hipótesis y devuelve evidencia del backend.','Ejecutar Research',async()=>{const d=await get('/api/v1/capabilities/delegate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contract:'sbt-v1',capability:'sbt',message:'Analiza EURUSD H1 y devuelve hipótesis, riesgos y siguiente prueba.',source:'sbt-web',mode:'research-only'})});return d.research||d;});
 addAction('evolution','Evolution Engine · control','Compara experimentos persistidos y muestra el próximo candidato.','Comparar evidencia',async()=>{const d=await get('/api/v1/evolution/intraday-compare?symbol=EURUSD');return 'Combinaciones con evidencia: '+(d.evidence_combinations??0)+' · elegibles: '+(d.eligible_combinations??0)+' · siguiente: '+(d.next_action||'—');});
 addAction('validation','Virtual Validation · ejecución','Ejecuta la validación virtual reproducible del backend.','Ejecutar validación',async()=>{const d=await get('/api/v1/validation/virtual');return 'P/L '+Number(d.realized_pnl||0).toFixed(2)+' · DD '+Number(d.max_drawdown_pct||0).toFixed(2)+'% · aceptadas '+(d.accepted_operations??0)+' · rechazadas '+(d.rejected_operations??0)+' · real_money='+d.real_money;});
 addAction('ai-bot-lab','AI Bot Lab · análisis','Ejecuta análisis del estado actual del bot.','Analizar bot',async()=>get('/api/v1/ai-bot-lab/analyze',{method:'POST'}));
 addAction('matrix','SBT Market Matrix · scanner','Ejecuta el scanner multiactivo y muestra los candidatos verificables.','Escanear mercado',async()=>{const d=await get('/api/v1/sbt/market-intelligence/scan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({symbols:['EURUSD','GBPUSD','USDJPY','XAUUSD','BTCUSD','SPX500','NAS100','AAPL','NVDA'],timeframe:'H1',limit:120})});return 'Scan: '+(d.rows||[]).length+' activos · proveedor '+(d.provider||'—')+'.';});
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else setTimeout(boot,0);
})();