(() => {
  const API=(window.SBT_API_URL||'https://bitey-system-bots-trading-api.onrender.com').replace(/\/$/,'');
  window.SBT_LIVE_TRADING_ENABLED=false;window.SBT_SAFETY={live:false,real_money:false,broker_orders:0};
  const ASSET_VERSION='20260912algo1';
  function banner(){const el=document.createElement('div');el.textContent='RESEARCH / DEMO ONLY · LIVE=false · REAL_MONEY=false · BROKER_ORDERS=0';el.style.cssText='position:fixed;bottom:0;left:0;right:0;z-index:9999;padding:8px;text-align:center;background:#111;color:#fff;font:600 12px system-ui;letter-spacing:.04em';document.body.appendChild(el)}
  async function health(){try{const r=await fetch(API+'/api/v1/system');if(!r.ok)throw new Error('HTTP '+r.status);return r.json()}catch(_){return null}}
  function loadWebTrader(){if(window.BiteyWebTrader){window.BiteyWebTrader.init();loadChartInteractions();loadMarketUniverse();loadM1Timeframe();loadBotBridge();loadDemoExecution();loadMarketPulse();loadAlgorithmicEngine();return}if(document.querySelector('script[data-bitey-web-trader]'))return;const s=document.createElement('script');s.src='/web-trader.js?v='+ASSET_VERSION;s.defer=true;s.dataset.biteyWebTrader='1';document.head.appendChild(s);s.addEventListener('load',()=>{loadChartInteractions();loadMarketUniverse();loadM1Timeframe();loadBotBridge();loadDemoExecution();loadMarketPulse();loadAlgorithmicEngine()},{once:true})}
  function loadChartInteractions(){if(document.querySelector('script[data-bitey-chart-interactions]'))return;const s=document.createElement('script');s.src='/chart-interactions.js?v='+ASSET_VERSION;s.defer=true;s.dataset.biteyChartInteractions='1';document.head.appendChild(s)}
  function loadMarketUniverse(){if(window.BiteyMarketUniverse){setTimeout(()=>window.BiteyMarketUniverse.init(),150);return}if(document.querySelector('script[data-bitey-market-universe]'))return;const s=document.createElement('script');s.src='/market-universe.js?v='+ASSET_VERSION;s.defer=true;s.dataset.biteyMarketUniverse='1';document.head.appendChild(s)}
  function loadM1Timeframe(){if(document.querySelector('script[data-bitey-m1-timeframe]'))return;const s=document.createElement('script');s.src='/m1-timeframe.js?v='+ASSET_VERSION;s.defer=true;s.dataset.biteyM1Timeframe='1';document.head.appendChild(s)}
  function loadBotBridge(){if(window.BiteySBTBotBridge){window.BiteySBTBotBridge.init();return}if(document.querySelector('script[data-bitey-bot-bridge]'))return;const s=document.createElement('script');s.src='/bot-bridge.js?v='+ASSET_VERSION;s.defer=true;s.dataset.biteyBotBridge='1';document.head.appendChild(s)}
  function loadDemoExecution(){if(window.BiteySBTDemoExecution){window.BiteySBTDemoExecution.init();return}if(document.querySelector('script[data-bitey-demo-execution]'))return;const s=document.createElement('script');s.src='/demo-execution.js?v='+ASSET_VERSION;s.defer=true;s.dataset.biteyDemoExecution='1';document.head.appendChild(s)}
  function loadMarketPulse(){if(window.BiteyMarketPulse){window.BiteyMarketPulse.init();return}if(document.querySelector('script[data-bitey-market-pulse]'))return;const s=document.createElement('script');s.src='/market-pulse.js?v='+ASSET_VERSION;s.defer=true;s.dataset.biteyMarketPulse='1';document.head.appendChild(s)}
  function loadAlgorithmicEngine(){if(window.BiteySBTAlgorithmic){window.BiteySBTAlgorithmic.init();return}if(document.querySelector('script[data-bitey-algorithmic]'))return;const s=document.createElement('script');s.src='/algorithmic-engine.js?v='+ASSET_VERSION;s.defer=true;s.dataset.biteyAlgorithmic='1';document.head.appendChild(s)}
  function loadTradingMode(){if(window.BiteySBTTradingMode){window.BiteySBTTradingMode.init();return}if(document.querySelector('script[data-bitey-trading-mode]'))return;const s=document.createElement('script');s.src='/trading-mode.js?v='+ASSET_VERSION;s.defer=true;document.head.appendChild(s);s.dataset.biteyTradingMode='1'}
  function installWebTraderStyles(){if(document.getElementById('sbt-web-trader-styles'))return;const style=document.createElement('style');style.id='sbt-web-trader-styles';style.textContent='#bot-lab-page.web-trader-only>.hero,#bot-lab-page.web-trader-only>.lab-controls{display:none!important}#bot-lab-page.web-trader-only .mt-shell{margin-top:0}#bot-lab-page.web-trader-only .mt-body{min-height:calc(100vh - 185px)}#bot-lab-page.web-trader-only .chart-wrap{min-height:calc(100vh - 395px)}#bot-lab-page.web-trader-only .mt-chart{min-height:calc(100vh - 395px)}';document.head.appendChild(style)}
  async function openThesisLab(){if(document.getElementById('thesis-lab-page'))return activateThesisLab();const main=document.querySelector('main.main');if(!main)return;const r=await fetch('/thesis-lab.html',{cache:'no-store'});if(!r.ok)throw new Error('Thesis Lab HTTP '+r.status);const wrap=document.createElement('div');wrap.innerHTML=await r.text();const section=wrap.querySelector('#thesis-lab-page');if(!section)throw new Error('Thesis Lab markup missing');main.appendChild(section);Array.from(wrap.querySelectorAll('script')).forEach(s=>{const n=document.createElement('script');n.textContent=s.textContent;document.body.appendChild(n)});activateThesisLab()}
  function activateThesisLab(){closeMobileMenu();document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));const p=document.getElementById('thesis-lab-page');if(p)p.classList.add('active');const title=document.getElementById('title');if(title)title.textContent='Mathematical Thesis Lab';document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.page==='thesis-lab'))}
  function installThesisNav(){const nav=document.querySelector('.nav');if(!nav||nav.querySelector('[data-page="thesis-lab"]'))return;const small=Array.from(nav.querySelectorAll('small')).find(x=>x.textContent.trim().toLowerCase()==='build');const b=document.createElement('button');b.dataset.page='thesis-lab';b.textContent='∑ Mathematical Thesis Lab';b.addEventListener('click',()=>openThesisLab().catch(e=>console.error(e)));if(small)small.insertAdjacentElement('afterend',b);else nav.appendChild(b)}
  async function openBotLab(){if(document.getElementById('bot-lab-page'))return activateBotLab();const main=document.querySelector('main.main');if(!main)return;const r=await fetch('/bot-lab.html',{cache:'no-store'});if(!r.ok)throw new Error('Bot Lab HTTP '+r.status);const wrap=document.createElement('div');wrap.innerHTML=await r.text();const section=wrap.querySelector('#bot-lab-page');if(!section)throw new Error('Bot Lab markup missing');main.appendChild(section);Array.from(wrap.querySelectorAll('script')).forEach(s=>{const n=document.createElement('script');n.textContent=s.textContent;document.body.appendChild(n)});activateBotLab()}
  function closeMobileMenu(){const side=document.getElementById('side');if(!side)return;side.classList.remove('open');side.style.removeProperty('transform');side.style.removeProperty('pointer-events')}
  function activateBotLab(){closeMobileMenu();document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));const p=document.getElementById('bot-lab-page');if(p){p.classList.add('active');p.classList.remove('web-trader-only')}const title=document.getElementById('title');if(title)title.textContent='Bot Lab';document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.page==='bots'));const status=document.getElementById('apiStatus');if(status)status.textContent='Bot Lab connected · live trading disabled';loadWebTrader();loadTradingMode()}
  async function openWebTrader(){await openBotLab();installWebTraderStyles();const p=document.getElementById('bot-lab-page');if(p)p.classList.add('web-trader-only');const title=document.getElementById('title');if(title)title.textContent='Web Trader';document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.page==='web-trader'));loadWebTrader();loadBotBridge();loadDemoExecution();loadMarketPulse();loadAlgorithmicEngine()}
  function installBotLabNav(){const nav=document.querySelector('.nav');if(!nav||nav.querySelector('[data-page="bots"]'))return;const small=Array.from(nav.querySelectorAll('small')).find(x=>x.textContent.trim().toLowerCase()==='workspace');const b=document.createElement('button');b.dataset.page='bots';b.textContent='◉ Bot Lab';b.addEventListener('click',()=>openBotLab().catch(e=>console.error(e)));if(small)small.insertAdjacentElement('afterend',b);else nav.appendChild(b)}
  function installWebTraderNav(){const nav=document.querySelector('.nav');if(!nav||nav.querySelector('[data-page="web-trader"]'))return;const bot=nav.querySelector('[data-page="bots"]');const b=document.createElement('button');b.dataset.page='web-trader';b.textContent='▣ Web Trader';b.addEventListener('click',()=>openWebTrader().catch(e=>console.error(e)));if(bot)bot.insertAdjacentElement('afterend',b);else nav.appendChild(b)}
  function interceptExistingBotButton(){document.querySelectorAll('[data-page="bots"]').forEach(b=>{if(b.dataset.botLabWired)return;b.dataset.botLabWired='1';b.addEventListener('click',event=>{event.preventDefault();event.stopImmediatePropagation();closeMobileMenu();openBotLab().catch(e=>console.error(e))},true)})}
  function expose(){window.BiteySBT={api:API,safety:window.SBT_SAFETY,health,async validation(){const r=await fetch(API+'/api/v1/validation/virtual',{method:'POST',headers:{'content-type':'application/json'},body:'{}'});if(!r.ok)throw new Error('Validation HTTP '+r.status);return r.json()},async strategyRegistry(){const r=await fetch(API+'/api/v1/strategy/registry');if(!r.ok)throw new Error('Registry HTTP '+r.status);return r.json()},async riskGateEvaluate(payload){const r=await fetch(API+'/api/v1/strategy/risk-gate/evaluate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw new Error('Risk Gate HTTP '+r.status);return r.json()},openThesisLab,openBotLab,openWebTrader}}
  function boot(){expose();banner();installThesisNav();installBotLabNav();installWebTraderNav();interceptExistingBotButton();health()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();