(() => {
  const API = (window.SBT_API_URL || 'https://bitey-system-bots-trading-api.onrender.com').replace(/\/$/, '');
  const state = { symbol:'EURUSD', timeframe:'M5', candles:[], quote:null, analysis:null, timer:null, ws:null, feedState:'OFFLINE', firstTickReceived:false, viewCount:120, viewEnd:null, source:'none', provider:'none', error:null, execution_enabled:false, live:false, real_money:false };
  window.BiteySBTMarketState = state;
  const el=id=>document.getElementById(id), setText=(id,v)=>{const n=el(id);if(n)n.textContent=v;}, num=(v,d=5)=>Number.isFinite(Number(v))?Number(v).toFixed(d):'—';
  const sourceName=v=>String(v||'none').trim().toLowerCase()||'none';
  const sourceLabel=()=>state.source&&state.source!=='none'?state.source.toUpperCase():'MARKET OFFLINE';
  function emit(){ window.dispatchEvent(new CustomEvent('bitesbt:market-state',{detail:{symbol:state.symbol,timeframe:state.timeframe,source:state.source,provider:state.provider,state:state.feedState,error:state.error,candle_count:state.candles.length,execution_enabled:false,live:false,real_money:false}})); }
  function setSource(v){state.source=sourceName(v);state.provider=state.source;}
  function normalize(c){const time=c.time??c.timestamp??c.datetime??c.t;return {time:Number(time)>1e12?Number(time)/1000:Number(time),open:Number(c.open??c.o),high:Number(c.high??c.h),low:Number(c.low??c.l),close:Number(c.close??c.c),volume:Number(c.volume??c.tick_volume??c.v??0)};}
  function validCandles(cs){return cs.map(normalize).filter(c=>Number.isFinite(c.time)&&[c.open,c.high,c.low,c.close].every(Number.isFinite)).sort((a,b)=>a.time-b.time);}
  function visibleCandles(){const total=state.candles.length;if(!total)return {candles:[],start:0,end:0};const count=Math.max(20,Math.min(Number(state.viewCount)||120,total));const end=Math.max(count,Math.min(state.viewEnd==null?total:state.viewEnd,total));return {candles:state.candles.slice(end-count,end),start:end-count,end};}
  function clampView(){state.viewCount=Math.max(20,Math.min(Math.round(Number(state.viewCount)||120),Math.max(20,state.candles.length||20)));if(state.viewEnd!=null){const count=Math.min(state.viewCount,state.candles.length);state.viewEnd=Math.max(count,Math.min(Math.round(state.viewEnd),state.candles.length));if(state.viewEnd>=state.candles.length)state.viewEnd=null;}}
  function resetView(){state.viewCount=Math.min(120,Math.max(20,state.candles.length||20));state.viewEnd=null;}
  function ema(v,p){if(v.length<p)return null;let x=v.slice(0,p).reduce((a,b)=>a+b,0)/p;const a=2/(p+1);for(let i=p;i<v.length;i++)x=a*v[i]+(1-a)*x;return x;}
  function rsi(v,p=14){if(v.length<=p)return null;let g=0,l=0;for(let i=1;i<=p;i++){const d=v[i]-v[i-1];g+=Math.max(d,0);l+=Math.max(-d,0);}let ag=g/p,al=l/p;for(let i=p+1;i<v.length;i++){const d=v[i]-v[i-1];ag=(ag*(p-1)+Math.max(d,0))/p;al=(al*(p-1)+Math.max(-d,0))/p;}return al===0?100:100-100/(1+ag/al);}
  function atr(cs,p=14){if(cs.length<=p)return null;const tr=cs.slice(1).map((c,i)=>Math.max(c.high-c.low,Math.abs(c.high-cs[i].close),Math.abs(c.low-cs[i].close)));return tr.slice(-p).reduce((a,b)=>a+b,0)/p;}
  function indicators(cs){const c=cs.map(x=>x.close),a=ema(c,9),b=ema(c,21);return {ema9:a,ema21:b,rsi14:rsi(c),atr14:atr(cs),trend:a==null||b==null?'—':a>b?'ALCISTA':a<b?'BAJISTA':'LATERAL'};}
  function resizeCanvas(c){const r=c.getBoundingClientRect(),d=window.devicePixelRatio||1;c.width=Math.max(1,Math.floor(r.width*d));c.height=Math.max(1,Math.floor(r.height*d));return {w:r.width,h:r.height,dpr:d};}
  function drawChart(){const canvas=el('mtChart');if(!canvas||!state.candles.length)return;clampView();const {candles,start}=visibleCandles();const {w,h,dpr}=resizeCanvas(canvas),ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);const left=58,right=70,top=28,bottom=30,max=Math.max(...candles.map(c=>c.high)),min=Math.min(...candles.map(c=>c.low)),range=Math.max(max-min,1e-9),pad=range*.06,hi=max+pad,lo=min-pad,y=v=>top+(hi-v)/(hi-lo)*(h-top-bottom),step=(w-left-right)/candles.length,body=Math.max(2,step*.62);ctx.font='10px system-ui';ctx.textAlign='right';for(let i=0;i<=6;i++){const yy=top+i*(h-top-bottom)/6,p=hi-i*(hi-lo)/6;ctx.strokeStyle='#18222d';ctx.beginPath();ctx.moveTo(left,yy);ctx.lineTo(w-right,yy);ctx.stroke();ctx.fillStyle='#7d8997';ctx.fillText(p.toFixed(5),w-6,yy+3);}candles.forEach((c,i)=>{const x=left+i*step+step/2,up=c.close>=c.open;ctx.strokeStyle=up?'#52e6a2':'#ff7272';ctx.fillStyle=ctx.strokeStyle;ctx.beginPath();ctx.moveTo(x,y(c.high));ctx.lineTo(x,y(c.low));ctx.stroke();const a=y(Math.max(c.open,c.close)),b=y(Math.min(c.open,c.close));ctx.fillRect(x-body/2,a,body,Math.max(2,b-a));});ctx.fillStyle='#edf3f8';ctx.textAlign='left';ctx.font='bold 11px system-ui';ctx.fillText(`${state.symbol} · ${state.timeframe} · ${sourceLabel()}`,left,14);ctx.font='10px system-ui';ctx.fillStyle='#7d8997';ctx.fillText(`OHLC + live ticks · ${start+1}-${start+candles.length} / ${state.candles.length}`,left+190,14);}
  function setFeedState(s,detail=''){state.feedState=s;state.error=detail||null;const labels={HISTORICAL:'● HISTORICAL DATA',CONNECTING:'● CONNECTING LIVE FEED',LIVE:'● LIVE DATA',OFFLINE:'● MARKET OFFLINE'};setText('mtFeedStatus',`${labels[s]||labels.OFFLINE} · ${state.symbol} · ${state.timeframe}${detail?` · ${detail}`:''}`);if(s==='OFFLINE'){setSource('none');}emit();}
  function upsertCandle(c){const n=normalize(c);if(!Number.isFinite(n.time))return;const i=state.candles.findIndex(x=>x.time===n.time);if(i>=0)state.candles[i]=n;else state.candles.push(n);state.candles.sort((a,b)=>a.time-b.time);if(state.candles.length>500)state.candles=state.candles.slice(-500);clampView();updateIndicators();drawChart();emit();}
  async function loadCandles(runAnalysis=true){setFeedState('CONNECTING');try{const r=await fetch(`${API}/api/v1/market/candles/${encodeURIComponent(state.symbol)}?timeframe=${encodeURIComponent(state.timeframe)}&limit=200`,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const p=await r.json(),cs=validCandles(p.candles||[]);setSource(p.source||p.provider||'none');if(cs.length<20)throw new Error('insufficient candle data');state.candles=cs;state.error=null;resetView();const empty=el('mtChartEmpty');if(empty)empty.style.display='none';updateIndicators();drawChart();emit();if(runAnalysis)await analyzeSameSnapshot();if(!state.firstTickReceived)setFeedState('HISTORICAL');}catch(e){state.candles=[];state.analysis=null;state.viewEnd=null;setSource('none');const empty=el('mtChartEmpty');if(empty){empty.style.display='grid';empty.textContent='MARKET OFFLINE · no invented market data';}drawChart();if(!state.firstTickReceived)setFeedState('OFFLINE',e.message);setText('mtChange',e.message);emit();}}
  async function analyzeSameSnapshot(){if(!state.candles.length)return;try{const r=await fetch(`${API}/api/v1/sbt/market-intelligence/analyze`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({symbol:state.symbol,timeframe:state.timeframe,candles:state.candles,capital:10000,language:'es',event:'market_structure',evidence:[{source:state.source||'none',contract:'sbt-candles-v1',snapshot_candles:state.candles.length}]})});if(!r.ok)throw new Error(`analysis HTTP ${r.status}`);state.analysis=await r.json();updateIndicators();}catch(_){}}
  function updateIndicators(){const i=indicators(state.candles);setText('mtEma9',num(i.ema9));setText('mtEma21',num(i.ema21));setText('mtRsi',i.rsi14==null?'—':i.rsi14.toFixed(1));setText('mtAtr',num(i.atr14,6));setText('mtTrend',i.trend);const q=state.quote;if(q){setText('mtBid',num(q.bid));setText('mtAsk',num(q.ask));setText('mtPrice',num(q.last??q.mid??q.bid));}}
  function connectQuoteStream(){if(state.ws){try{state.ws.close();}catch(_){}}state.firstTickReceived=false;state.quote=null;setFeedState('CONNECTING');const url=API.replace(/^http/,'ws')+`/api/v1/market/stream/${encodeURIComponent(state.symbol)}?timeframe=${encodeURIComponent(state.timeframe)}`;try{const ws=new WebSocket(url);state.ws=ws;ws.onmessage=e=>{try{const d=JSON.parse(e.data);if(d.source||d.provider)setSource(d.source||d.provider);if(Array.isArray(d.historical_candles)){const h=validCandles(d.historical_candles);if(h.length){const latest=state.viewEnd==null;state.candles=h;if(latest)resetView();else clampView();updateIndicators();drawChart();emit();}}if(d.state==='OFFLINE'){setFeedState('OFFLINE',d.error||'provider unavailable');return;}if(d.state!=='LIVE'||!(d.mid||d.bid||d.ask))return;state.firstTickReceived=true;state.quote=d;state.error=null;setFeedState('LIVE');if(d.candle)upsertCandle(d.candle);else{updateIndicators();drawChart();emit();}setText('mtChange',`Bid ${num(d.bid)} · Ask ${num(d.ask)} · spread ${num(d.spread,6)}`);}catch(_){}};ws.onclose=()=>{if(state.ws===ws){if(!state.firstTickReceived)setFeedState('OFFLINE','stream closed');setTimeout(()=>connectQuoteStream(),3000);}};ws.onerror=()=>{if(!state.firstTickReceived)setFeedState('OFFLINE','WebSocket error');};}catch(_){setFeedState('OFFLINE','WebSocket unavailable');}}
  function refreshSourceLabels(){const label=sourceLabel();document.querySelectorAll('#bot-lab-page small').forEach(n=>{if(n.textContent==='BiQuote'||n.dataset.marketSourceLabel==='1'){n.textContent=label;n.dataset.marketSourceLabel='1';}});setText('mtTf',`${state.timeframe} · ${label}`);}
  function setup(){const page=el('bot-lab-page');if(!page||page.dataset.webTraderReady)return;page.dataset.webTraderReady='1';document.querySelectorAll('#bot-lab-page [data-tf]').forEach(b=>b.addEventListener('click',()=>{state.timeframe=b.dataset.tf;state.viewEnd=null;document.querySelectorAll('#bot-lab-page [data-tf]').forEach(x=>x.classList.toggle('active',x===b));connectQuoteStream();loadCandles(true);}));const refresh=el('mtRefresh');if(refresh)refresh.addEventListener('click',()=>loadCandles(true));const symbols=['EURUSD','GBPUSD','USDJPY','XAUUSD','BTCUSD'],watch=el('mtWatchBody');if(watch)watch.innerHTML=symbols.map(s=>`<tr data-symbol="${s}" class="${s===state.symbol?'selected':''}"><td><span class="mt-symbol">${s}</span><small data-market-source-label="1">${sourceLabel()}</small></td><td>—</td></tr>`).join('');if(watch)watch.querySelectorAll('[data-symbol]').forEach(row=>row.addEventListener('click',()=>{state.symbol=row.dataset.symbol;state.viewEnd=null;resetView();watch.querySelectorAll('tr').forEach(r=>r.classList.toggle('selected',r===row));setText('mtPair',state.symbol);setText('mtOverlay',`Bitey SBT · ${state.symbol} · ${state.timeframe}`);state.quote=null;connectQuoteStream();loadCandles(true);}));setText('mtPair',state.symbol);setText('mtTf',`${state.timeframe} · ${sourceLabel()}`);setText('mtOverlay',`Bitey SBT · ${state.symbol} · ${state.timeframe}`);loadCandles(true);connectQuoteStream();clearInterval(state.timer);state.timer=setInterval(()=>loadCandles(true),10000);window.addEventListener('resize',drawChart);emit();}
  window.BiteyWebTrader={init:setup,state,drawChart,visibleCandles,resetView,clampView};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(setup,0));else setTimeout(setup,0);
})();
